GRANT ALL ON *.* TO 'root'@'%' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD';

create user '$MYSQL_USER'@'%' identified by '$MYSQL_PASSWORD';

CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE; 
GRANT ALL ON $MYSQL_DATABASE.* TO '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
FLUSH PRIVILEGES;